### ISSUE TITLE
OTA Support for CC2420 MSP-430 | Zolertia Z1

### ISSUE THREAD

**Issue by kaleemullah360** [msolters/ota-server#3]
Dear @msolters ,

**Can we program Zolertia Z1 mote over the air ?** 

**it's [specifications](https://github.com/kaleemullah360/kontiki/blob/master/examples/zolertia/zolertia-z1.md) are:**

> Z1 is equipped with a second generation MSP430F2617 low power microcontroller, which features a powerful 16-bit RISC CPU @16MHz clock speed, built-in clock factory calibration, 8KB RAM and a 92KB Flash memory. Also includes the well known CC2420 transceiver, IEEE 802.15.4 compliant, which operates at 2.4GHz with an effective data rate of 250Kbps. Z1 hardware selection guarantees the maximum efficience and robustness with low energy cost.

please guide me, I'll be very thankful to you.

**Comment by msolters** [comment]
This repository is the wrong place to ask.  The nature of the OTA _server_ is platform-agnostic.  It is literally just a simple NodeJS server.  To program any mote -- like the Z1 or the Sensortag or whatever -- does not involve this repository at all.  It's 100% a firmware problem to port the self-programming routines to a new processor.

That being said, what you should be looking at is this code: https://github.com/msolters/contiki/tree/master/examples/cc26xx-ota-bootloader

That firmware will work with the OTA server here.  But you'll have to try compiling it for your Z1 mote first, and then recursively track down problems from there.  I don't know how the Z1 processor's code compiles, or how the vector tables are laid out, etc.  That will be on you to research from the datasheets.

In general, you're gonna have to write a new linker script for that processor so that the OTA bootloader firmware can live in the appropriate sector of memory, and so that your statically linked application code knows the flash offset address the bootloader copies it to.

You should really refer to my blog post to understand the underlying architecture and download/overwrite mechanism.  It will help you understand what things need porting and what things don't.  http://marksolters.com/programming/2016/06/07/contiki-ota.html

**Comment by kaleemullah360** [comment]
@msolters thanks for your help. I understand the core problem. 👍

**Comment by msolters** [comment]
Yes, I can help you with questions about porting Contiki (possibly).

**Comment by kaleemullah360** [comment]
@msolters, OTA support for new devices i.e. Zolertia Zoul RE mote. but not for Z1 mote. and I've only z1 devices, z1 mote ROM is 92KB.
please view:
[OTA for Zoul](https://github.com/sics-iot/sparrow)

**Comment by msolters** [comment]
Well, first off, you'll have to change the intended size of an OTA image to match that 92KB.  I use 100KB in my code as the size of an OTA image which obviously won't fit your MCU.

But I can't tell you anything about Sparrow.  That has nothing to do with the OTA code I have written.

**Comment by kaleemullah360** [comment]
@msolters, the major problem is its `ROM` size. more often I've to deal with `ROM` overflows problem (do tweaks, reduces functions, variables, micro optimizations).
**92KB ROM Image = > Boot Loader + Mote flashing Image + Application Image.**
for now my goal is to write a bootloader which re-flash with new image. in short with what parameters z1 flash `IHEX` file in its `ROM`. and can you clear me whether RTC (Real Time Clock) is important for this process. cause z1 has no real time clock hence its clock get reset up one reboot or reset.

if you just point me what document to read. that'll save my lots of time. like [this](http://www.ti.com/lit/ug/slau319l/slau319l.pdf) 

Thank you   :+1:
